[tools]
aws-cli = { version = "latest", symlink_bins = "true" }
terraform = "latest"
tflint = "latest"
tfsec = "latest"

[tasks."tfi"]
description = "Runs terraform init"
run = "terraform init"

[tasks."tfp"]
description = "Runs terraform plan"
run = "terraform plan"

[tasks."tfa"]
description = "Runs terraform apply"
run = "terraform apply"

[tasks."tfv"]
description = "Runs terraform validate"
run = "terraform validate"

[tasks."tff"]
description = "runs terraform fmt"
run = "terraform fmt"

[tasks."tfch"]
description = "format AND validate all in one!"
depends = ["tff", "tfv"]



