[tools]
terraform = "1.15.1"
tflint = "0.62.0"

[tasks."tfi"]
description = "Runs terraform init"
run = "terraform init"

[tasks."tfp"]
description = "Runs terraform plan"
run = "terraform plan"

[tasks."tfa"]
description = "Runs terraform apply"
run = "terraform apply"

[tasks."tfv"]
description = "Runs terraform validate"
run = "terraform validate"

[tasks."tff"]
description = "runs terraform fmt"
run = "terraform fmt"

[tasks. "tfl"]
description = "runs tflint"
run = "tflint"

[tasks."tfch"]
description = "lint AND format AND validate all in one!"
depends = ["tfl","tff", "tfv"]