[tools]
aws-cli = { version = "2.34", symlink_bins = "true" }
jq = "1.8.1"
hk = "1.36.0"
pkl = "0.31.1"
pnpm = "11.1"

[tasks.pre-commit]
run = "hk run pre-commit"

[tasks.hk-install]
description = "Bootstraps a repo with hk pre-commit"
run = "hk install --mise"
