[tools]
aws-cli = { version = "2.34", symlink_bins = "true" }
jq = "1.8" 
uv = "0.11" # python package manager

hk = "1.36" # mise sister package for pre-commit
pkl = "0.31" # needed for hk

[tasks.pre-commit]
run = "hk run pre-commit"

[tasks.hk-install]
description = "Bootstraps a repo with hk pre-commit"
run = "hk install --mise"
